using System.ComponentModel.DataAnnotations;

namespace IPOPHLTrademark.Client.Models
{

    public class NationalityDataModel
    {
        public int NationalityId { get; set; }
        public string NationalityName { get; set; }
    }

    public class NationalityModel
    {
        public List<NationalityDataModel> NationalityList { get; }

        public NationalityModel() 
        {
            NationalityList = new List<NationalityDataModel>()
            {
                new NationalityDataModel() { NationalityId = 1, NationalityName = "Filipino" },
                new NationalityDataModel() { NationalityId = 2, NationalityName = "Afghan" },
                new NationalityDataModel() { NationalityId = 3, NationalityName = "Albanian" },
                new NationalityDataModel() { NationalityId = 4, NationalityName = "Algerian" },
                new NationalityDataModel() { NationalityId = 5, NationalityName = "Andorran" },
                new NationalityDataModel() { NationalityId = 6, NationalityName = "Angolan" },
                new NationalityDataModel() { NationalityId = 7, NationalityName = "Citizen of Antigua and Barbuda" },
                new NationalityDataModel() { NationalityId = 8, NationalityName = "Argentine" },
                new NationalityDataModel() { NationalityId = 9, NationalityName = "Armenian" },
                new NationalityDataModel() { NationalityId = 10, NationalityName = "Australian" },
                new NationalityDataModel() { NationalityId = 11, NationalityName = "Austrian" },
                new NationalityDataModel() { NationalityId = 12, NationalityName = "Azerbaijani" },
                new NationalityDataModel() { NationalityId = 13, NationalityName = "Bahamian" },
                new NationalityDataModel() { NationalityId = 14, NationalityName = "Bahraini" },
                new NationalityDataModel() { NationalityId = 15, NationalityName = "Bangladeshi" },
                new NationalityDataModel() { NationalityId = 16, NationalityName = "Barbadian" },
                new NationalityDataModel() { NationalityId = 17, NationalityName = "Belarusian" },
                new NationalityDataModel() { NationalityId = 18, NationalityName = "Belgian" },
                new NationalityDataModel() { NationalityId = 19, NationalityName = "Belizean" },
                new NationalityDataModel() { NationalityId = 20, NationalityName = "Beninese" },
                new NationalityDataModel() { NationalityId = 21, NationalityName = "Bhutanese" },
                new NationalityDataModel() { NationalityId = 22, NationalityName = "Bolivian" },
                new NationalityDataModel() { NationalityId = 23, NationalityName = "Citizen Bosnia and Herzegovina" },
                new NationalityDataModel() { NationalityId = 24, NationalityName = "Botswanan" },
                new NationalityDataModel() { NationalityId = 25, NationalityName = "Brazilian" },
                new NationalityDataModel() { NationalityId = 26, NationalityName = "Bruneian" },
                new NationalityDataModel() { NationalityId = 27, NationalityName = "Bulgarian" },
                new NationalityDataModel() { NationalityId = 28, NationalityName = "Burkinan" },
                new NationalityDataModel() { NationalityId = 29, NationalityName = "Burundian" },
                new NationalityDataModel() { NationalityId = 30, NationalityName = "Cabo Verde" },
                new NationalityDataModel() { NationalityId = 31, NationalityName = "Cambodian" },
                new NationalityDataModel() { NationalityId = 32, NationalityName = "Cameroonian" },
                new NationalityDataModel() { NationalityId = 33, NationalityName = "Canadian" },
                new NationalityDataModel() { NationalityId = 34, NationalityName = "Central African Republic" },
                new NationalityDataModel() { NationalityId = 35, NationalityName = "Chadian" },
                new NationalityDataModel() { NationalityId = 36, NationalityName = "Chilean" },
                new NationalityDataModel() { NationalityId = 37, NationalityName = "Chinese" },
                new NationalityDataModel() { NationalityId = 38, NationalityName = "Colombian" },
                new NationalityDataModel() { NationalityId = 39, NationalityName = "Comoran" },
                new NationalityDataModel() { NationalityId = 40, NationalityName = "Congolese" },
                new NationalityDataModel() { NationalityId = 41, NationalityName = "Costa Rican" },
                new NationalityDataModel() { NationalityId = 42, NationalityName = "Croatian" },
                new NationalityDataModel() { NationalityId = 43, NationalityName = "Cuban" },
                new NationalityDataModel() { NationalityId = 44, NationalityName = "Cypriot" },
                new NationalityDataModel() { NationalityId = 45, NationalityName = "Czech Republic" },
                new NationalityDataModel() { NationalityId = 46, NationalityName = "Democratic Republic of the Congo" },
                new NationalityDataModel() { NationalityId = 47, NationalityName = "Denmark" },
                new NationalityDataModel() { NationalityId = 48, NationalityName = "Djibouti" },
                new NationalityDataModel() { NationalityId = 49, NationalityName = "Dominica" },
                new NationalityDataModel() { NationalityId = 50, NationalityName = "Dominican Republic" },
                new NationalityDataModel() { NationalityId = 51, NationalityName = "East Timor" },
                new NationalityDataModel() { NationalityId = 52, NationalityName = "Ecuador" },
                new NationalityDataModel() { NationalityId = 53, NationalityName = "Egypt" },
                new NationalityDataModel() { NationalityId = 54, NationalityName = "El Salvador" },
                new NationalityDataModel() { NationalityId = 55, NationalityName = "Equatorial Guinea" },
                new NationalityDataModel() { NationalityId = 56, NationalityName = "Eritrea" },
                new NationalityDataModel() { NationalityId = 57, NationalityName = "Estonia" },
                new NationalityDataModel() { NationalityId = 58, NationalityName = "Eswatini" },
                new NationalityDataModel() { NationalityId = 59, NationalityName = "Ethiopia" },
                new NationalityDataModel() { NationalityId = 60, NationalityName = "Fiji" },
                new NationalityDataModel() { NationalityId = 61, NationalityName = "Finland" },
                new NationalityDataModel() { NationalityId = 62, NationalityName = "France" },
                new NationalityDataModel() { NationalityId = 63, NationalityName = "Gabon" },
                new NationalityDataModel() { NationalityId = 64, NationalityName = "Gambia" },
                new NationalityDataModel() { NationalityId = 65, NationalityName = "Georgia" },
                new NationalityDataModel() { NationalityId = 66, NationalityName = "Germany" },
                new NationalityDataModel() { NationalityId = 67, NationalityName = "Ghana" },
                new NationalityDataModel() { NationalityId = 68, NationalityName = "Greece" },
                new NationalityDataModel() { NationalityId = 69, NationalityName = "Grenada" },
                new NationalityDataModel() { NationalityId = 70, NationalityName = "Guatemala" },
                new NationalityDataModel() { NationalityId = 71, NationalityName = "Guinea" },
                new NationalityDataModel() { NationalityId = 72, NationalityName = "Guinea-Bissau" },
                new NationalityDataModel() { NationalityId = 73, NationalityName = "Guyana" },
                new NationalityDataModel() { NationalityId = 74, NationalityName = "Haiti" },
                new NationalityDataModel() { NationalityId = 75, NationalityName = "Honduras" },
                new NationalityDataModel() { NationalityId = 76, NationalityName = "Hungary" },
                new NationalityDataModel() { NationalityId = 77, NationalityName = "Iceland" },
                new NationalityDataModel() { NationalityId = 78, NationalityName = "India" },
                new NationalityDataModel() { NationalityId = 79, NationalityName = "Indonesia" },
                new NationalityDataModel() { NationalityId = 80, NationalityName = "Iran" },
                new NationalityDataModel() { NationalityId = 81, NationalityName = "Iraq" },
                new NationalityDataModel() { NationalityId = 82, NationalityName = "Ireland" },
                new NationalityDataModel() { NationalityId = 83, NationalityName = "Israel" },
                new NationalityDataModel() { NationalityId = 84, NationalityName = "Italy" },
                new NationalityDataModel() { NationalityId = 85, NationalityName = "Ivory Coast" },
                new NationalityDataModel() { NationalityId = 86, NationalityName = "Jamaica" },
                new NationalityDataModel() { NationalityId = 87, NationalityName = "Japan" },
                new NationalityDataModel() { NationalityId = 89, NationalityName = "Jordan" },
                new NationalityDataModel() { NationalityId = 89, NationalityName = "Kazakhstan" },
                new NationalityDataModel() { NationalityId = 90, NationalityName = "Kenya" },
                new NationalityDataModel() { NationalityId = 91, NationalityName = "Kiribati" },
                new NationalityDataModel() { NationalityId = 92, NationalityName = "Kosovo" },
                new NationalityDataModel() { NationalityId = 93, NationalityName = "Kuwait" },
                new NationalityDataModel() { NationalityId = 94, NationalityName = "Kyrgyzstan" },
                new NationalityDataModel() { NationalityId = 95, NationalityName = "Laos" },
                new NationalityDataModel() { NationalityId = 96, NationalityName = "Latvia" },
                new NationalityDataModel() { NationalityId = 97, NationalityName = "Lebanon" },
                new NationalityDataModel() { NationalityId = 98, NationalityName = "Lesotho" },
                new NationalityDataModel() { NationalityId = 99, NationalityName = "Liberia" },
                new NationalityDataModel() { NationalityId = 100, NationalityName = "Libya" },
                new NationalityDataModel() { NationalityId = 101, NationalityName = "Liechtenstein" },
                new NationalityDataModel() { NationalityId = 102, NationalityName = "Lithuania" },
                new NationalityDataModel() { NationalityId = 103, NationalityName = "Luxembourg" },
                new NationalityDataModel() { NationalityId = 104, NationalityName = "Madagascar" },
                new NationalityDataModel() { NationalityId = 105, NationalityName = "Malawi" },
                new NationalityDataModel() { NationalityId = 106, NationalityName = "Malaysia" },
                new NationalityDataModel() { NationalityId = 107, NationalityName = "Maldives" },
                new NationalityDataModel() { NationalityId = 108, NationalityName = "Mali" },
                new NationalityDataModel() { NationalityId = 109, NationalityName = "Malta" },
                new NationalityDataModel() { NationalityId = 110, NationalityName = "Marshall Islands" },
                new NationalityDataModel() { NationalityId = 111, NationalityName = "Mauritania" },
                new NationalityDataModel() { NationalityId = 112, NationalityName = "Mauritius" },
                new NationalityDataModel() { NationalityId = 113, NationalityName = "Mexico" },
                new NationalityDataModel() { NationalityId = 114, NationalityName = "Micronesia" },
                new NationalityDataModel() { NationalityId = 115, NationalityName = "Moldova" },
                new NationalityDataModel() { NationalityId = 116, NationalityName = "Monaco" },
                new NationalityDataModel() { NationalityId = 117, NationalityName = "Mongolia" },
                new NationalityDataModel() { NationalityId = 118, NationalityName = "Montenegro" },
                new NationalityDataModel() { NationalityId = 119, NationalityName = "Morocco" },
                new NationalityDataModel() { NationalityId = 120, NationalityName = "Mozambique" },
                new NationalityDataModel() { NationalityId = 121, NationalityName = "Myanmar" },
                new NationalityDataModel() { NationalityId = 122, NationalityName = "Namibia" },
                new NationalityDataModel() { NationalityId = 123, NationalityName = "Nauru" },
                new NationalityDataModel() { NationalityId = 124, NationalityName = "Nepal" },
                new NationalityDataModel() { NationalityId = 125, NationalityName = "Netherlands" },
                new NationalityDataModel() { NationalityId = 126, NationalityName = "New Zealand" },
                new NationalityDataModel() { NationalityId = 127, NationalityName = "Nicaragua" },
                new NationalityDataModel() { NationalityId = 128, NationalityName = "Niger" },
                new NationalityDataModel() { NationalityId = 129, NationalityName = "Nigeria" },
                new NationalityDataModel() { NationalityId = 130, NationalityName = "North Korea" },
                new NationalityDataModel() { NationalityId = 131, NationalityName = "North Macedonia" },
                new NationalityDataModel() { NationalityId = 132, NationalityName = "Norway" },
                new NationalityDataModel() { NationalityId = 133, NationalityName = "Oman" },
                new NationalityDataModel() { NationalityId = 134, NationalityName = "Pakistan" },
                new NationalityDataModel() { NationalityId = 135, NationalityName = "Palau" },
                new NationalityDataModel() { NationalityId = 136, NationalityName = "Palestine" },
                new NationalityDataModel() { NationalityId = 137, NationalityName = "Panama" },
                new NationalityDataModel() { NationalityId = 138, NationalityName = "Papua New Guinea" },
                new NationalityDataModel() { NationalityId = 139, NationalityName = "Paraguay" },
                new NationalityDataModel() { NationalityId = 140, NationalityName = "Peru" },
                new NationalityDataModel() { NationalityId = 141, NationalityName = "Poland" },
                new NationalityDataModel() { NationalityId = 142, NationalityName = "Portugal" },
                new NationalityDataModel() { NationalityId = 143, NationalityName = "Qatar" },
                new NationalityDataModel() { NationalityId = 144, NationalityName = "Romania" },
                new NationalityDataModel() { NationalityId = 145, NationalityName = "Russia" },
                new NationalityDataModel() { NationalityId = 146, NationalityName = "Rwanda" },
                new NationalityDataModel() { NationalityId = 147, NationalityName = "Saint Kitts and Nevis" },
                new NationalityDataModel() { NationalityId = 148, NationalityName = "Saint Lucia" },
                new NationalityDataModel() { NationalityId = 149, NationalityName = "Saint Vincent and the Grenadines" },
                new NationalityDataModel() { NationalityId = 150, NationalityName = "Samoa" },
                new NationalityDataModel() { NationalityId = 151, NationalityName = "San Marino" },
                new NationalityDataModel() { NationalityId = 152, NationalityName = "Sao Tome and Principe" },
                new NationalityDataModel() { NationalityId = 153, NationalityName = "Saudi Arabia" },
                new NationalityDataModel() { NationalityId = 154, NationalityName = "Senegal" },
                new NationalityDataModel() { NationalityId = 155, NationalityName = "Serbia" },
                new NationalityDataModel() { NationalityId = 156, NationalityName = "Seychelles" },
                new NationalityDataModel() { NationalityId = 157, NationalityName = "Sierra Leone" },
                new NationalityDataModel() { NationalityId = 158, NationalityName = "Singapore" },
                new NationalityDataModel() { NationalityId = 159, NationalityName = "Slovakia" },
                new NationalityDataModel() { NationalityId = 160, NationalityName = "Slovenia" },
                new NationalityDataModel() { NationalityId = 161, NationalityName = "Solomon Islands" },
                new NationalityDataModel() { NationalityId = 162, NationalityName = "Somalia" },
                new NationalityDataModel() { NationalityId = 163, NationalityName = "South Africa" },
                new NationalityDataModel() { NationalityId = 164, NationalityName = "South Korea" },
                new NationalityDataModel() { NationalityId = 165, NationalityName = "South Sudan" },
                new NationalityDataModel() { NationalityId = 166, NationalityName = "Spain" },
                new NationalityDataModel() { NationalityId = 167, NationalityName = "Sri Lanka" },
                new NationalityDataModel() { NationalityId = 168, NationalityName = "Sudan" },
                new NationalityDataModel() { NationalityId = 169, NationalityName = "Suriname" },
                new NationalityDataModel() { NationalityId = 170, NationalityName = "Sweden" },
                new NationalityDataModel() { NationalityId = 171, NationalityName = "Switzerland" },
                new NationalityDataModel() { NationalityId = 172, NationalityName = "Syria" },
                new NationalityDataModel() { NationalityId = 173, NationalityName = "Taiwan" },
                new NationalityDataModel() { NationalityId = 174, NationalityName = "Tajikistan" },
                new NationalityDataModel() { NationalityId = 175, NationalityName = "Tanzania" },
                new NationalityDataModel() { NationalityId = 176, NationalityName = "Thailand" },
                new NationalityDataModel() { NationalityId = 177, NationalityName = "Togo" },
                new NationalityDataModel() { NationalityId = 178, NationalityName = "Tonga" },
                new NationalityDataModel() { NationalityId = 179, NationalityName = "Trinidad and Tobago" },
                new NationalityDataModel() { NationalityId = 180, NationalityName = "Tunisia" },
                new NationalityDataModel() { NationalityId = 181, NationalityName = "Turkey" },
                new NationalityDataModel() { NationalityId = 182, NationalityName = "Turkmenistan" },
                new NationalityDataModel() { NationalityId = 183, NationalityName = "Tuvalu" },
                new NationalityDataModel() { NationalityId = 184, NationalityName = "Uganda" },
                new NationalityDataModel() { NationalityId = 185, NationalityName = "Ukraine" },
                new NationalityDataModel() { NationalityId = 186, NationalityName = "United Arab Emirates" },
                new NationalityDataModel() { NationalityId = 187, NationalityName = "United Kingdom" },
                new NationalityDataModel() { NationalityId = 189, NationalityName = "United States" },
                new NationalityDataModel() { NationalityId = 189, NationalityName = "Uruguay" },
                new NationalityDataModel() { NationalityId = 190, NationalityName = "Uzbekistan" },
                new NationalityDataModel() { NationalityId = 191, NationalityName = "Vanuatu" },
                new NationalityDataModel() { NationalityId = 192, NationalityName = "Vatican City" },
                new NationalityDataModel() { NationalityId = 193, NationalityName = "Venezuela" },
                new NationalityDataModel() { NationalityId = 194, NationalityName = "Vietnam" },
                new NationalityDataModel() { NationalityId = 195, NationalityName = "Yemen" },
                new NationalityDataModel() { NationalityId = 196, NationalityName = "Zambia" },
                new NationalityDataModel() { NationalityId = 197, NationalityName = "Zimbabwe" },
            };
        }
    }
    
}
